#!/bin/bash
#
# Ginto FRP Server Installation Script
# Installs and configures frps on the server
#
# Usage: sudo ./install_frps.sh
#

set -e

# Configuration
FRP_VERSION="${FRP_VERSION:-0.66.0}"
FRP_ARCH="${FRP_ARCH:-linux_amd64}"
FRP_DIR="/opt/frp"
FRP_CONFIG="/etc/frp"
FRP_USER="frp"
FRP_TOKEN="${FRP_AUTH_TOKEN:-$(openssl rand -hex 32)}"
FRP_DASHBOARD_PWD="${FRP_DASHBOARD_PWD:-$(openssl rand -hex 16)}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

log_info "Installing frp server (frps) version ${FRP_VERSION}..."

# Create frp user if not exists
if ! id "$FRP_USER" &>/dev/null; then
    log_info "Creating frp user..."
    useradd -r -s /bin/false -d "$FRP_DIR" "$FRP_USER"
fi

# Create directories
log_info "Creating directories..."
mkdir -p "$FRP_DIR"
mkdir -p "$FRP_CONFIG"
mkdir -p /var/log/frp

# Download frp
FRP_DOWNLOAD_URL="https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_${FRP_ARCH}.tar.gz"
FRP_TMP="/tmp/frp_${FRP_VERSION}.tar.gz"

if [[ ! -f "$FRP_DIR/frps" ]] || [[ "$1" == "--force" ]]; then
    log_info "Downloading frp from ${FRP_DOWNLOAD_URL}..."
    curl -sSL "$FRP_DOWNLOAD_URL" -o "$FRP_TMP"
    
    log_info "Extracting..."
    tar -xzf "$FRP_TMP" -C /tmp
    
    cp "/tmp/frp_${FRP_VERSION}_${FRP_ARCH}/frps" "$FRP_DIR/"
    cp "/tmp/frp_${FRP_VERSION}_${FRP_ARCH}/frpc" "$FRP_DIR/"
    chmod +x "$FRP_DIR/frps" "$FRP_DIR/frpc"
    
    rm -rf "/tmp/frp_${FRP_VERSION}_${FRP_ARCH}" "$FRP_TMP"
    
    log_success "frp binaries installed to $FRP_DIR"
else
    log_info "frps already installed, skipping download (use --force to reinstall)"
fi

# Create symlinks
ln -sf "$FRP_DIR/frps" /usr/local/bin/frps
ln -sf "$FRP_DIR/frpc" /usr/local/bin/frpc

# Create configuration file
log_info "Creating frps configuration..."
cat > "$FRP_CONFIG/frps.toml" << 'EOF'
# frps Server Configuration for Ginto.ai
# Generated by install_frps.sh

bindAddr = "0.0.0.0"
bindPort = 7000

# Virtual host settings
vhostHTTPPort = 8080
vhostHTTPSPort = 8443
subDomainHost = "ginto.ai"

# Authentication
auth.method = "token"
auth.token = "{{ .Envs.FRP_AUTH_TOKEN }}"

# TLS settings
transport.tls.force = false
transport.tls.disableCustomTLSFirstByte = true

# Connection settings
transport.maxPoolCount = 20
transport.tcpMux = true
transport.tcpMuxKeepaliveInterval = 30
transport.heartbeatTimeout = 90

# Allowed ports for TCP proxies
allowPorts = [
    { start = 6000, end = 6999 },
    { start = 8000, end = 8999 },
    { start = 9000, end = 9999 }
]

# Web dashboard (internal only)
webServer.addr = "127.0.0.1"
webServer.port = 7500
webServer.user = "admin"
webServer.password = "{{ .Envs.FRP_DASHBOARD_PWD }}"

# Prometheus metrics
enablePrometheus = true

# Logging
log.to = "/var/log/frp/frps.log"
log.level = "info"
log.maxDays = 7

# Detailed errors for debugging
detailedErrorsToClient = true
EOF

# Create environment file
log_info "Creating environment file..."
cat > "$FRP_CONFIG/frps.env" << EOF
FRP_AUTH_TOKEN=${FRP_TOKEN}
FRP_DASHBOARD_PWD=${FRP_DASHBOARD_PWD}
EOF
chmod 600 "$FRP_CONFIG/frps.env"

# Create systemd service
log_info "Creating systemd service..."
cat > /etc/systemd/system/ginto-frps.service << EOF
[Unit]
Description=Ginto FRP Server (frps)
Documentation=https://github.com/fatedier/frp
After=network.target

[Service]
Type=simple
User=root
Group=root
EnvironmentFile=$FRP_CONFIG/frps.env
ExecStart=$FRP_DIR/frps -c $FRP_CONFIG/frps.toml
Restart=always
RestartSec=5
LimitNOFILE=1048576
StandardOutput=append:/var/log/frp/frps.log
StandardError=append:/var/log/frp/frps.log

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/log/frp

[Install]
WantedBy=multi-user.target
EOF

# Set permissions
chown -R "$FRP_USER:$FRP_USER" "$FRP_DIR"
chown -R "$FRP_USER:$FRP_USER" /var/log/frp
chown -R root:root "$FRP_CONFIG"
chmod 700 "$FRP_CONFIG"

# Configure firewall
log_info "Configuring firewall..."
if command -v ufw &> /dev/null; then
    ufw allow 7000/tcp comment "frp client connections"
    ufw allow 8080/tcp comment "frp HTTP vhost"
    ufw allow 8443/tcp comment "frp HTTPS vhost"
    # Allow range for TCP proxies
    ufw allow 6000:6999/tcp comment "frp TCP proxy range"
    log_success "UFW rules added"
elif command -v firewall-cmd &> /dev/null; then
    firewall-cmd --permanent --add-port=7000/tcp
    firewall-cmd --permanent --add-port=8080/tcp
    firewall-cmd --permanent --add-port=8443/tcp
    firewall-cmd --permanent --add-port=6000-6999/tcp
    firewall-cmd --reload
    log_success "Firewalld rules added"
fi

# Reload systemd and start service
log_info "Starting frps service..."
systemctl daemon-reload
systemctl enable ginto-frps
systemctl restart ginto-frps

# Wait for service to start
sleep 2

# Check status
if systemctl is-active --quiet ginto-frps; then
    log_success "frps is running!"
else
    log_error "frps failed to start. Check logs: journalctl -u ginto-frps"
    exit 1
fi

# Print summary
echo ""
echo "=============================================="
log_success "FRP Server Installation Complete!"
echo "=============================================="
echo ""
echo "Configuration:"
echo "  Config file:    $FRP_CONFIG/frps.toml"
echo "  Environment:    $FRP_CONFIG/frps.env"
echo "  Logs:           /var/log/frp/frps.log"
echo ""
echo "Ports:"
echo "  Client port:    7000"
echo "  HTTP vhost:     8080"
echo "  HTTPS vhost:    8443"
echo "  Dashboard:      127.0.0.1:7500"
echo ""
echo "Authentication Token (save this!):"
echo "  ${FRP_TOKEN}"
echo ""
echo "Dashboard Password:"
echo "  ${FRP_DASHBOARD_PWD}"
echo ""
echo "Commands:"
echo "  Status:    systemctl status ginto-frps"
echo "  Logs:      tail -f /var/log/frp/frps.log"
echo "  Restart:   systemctl restart ginto-frps"
echo ""
echo "Next steps:"
echo "  1. Add Caddy config to proxy *.ginto.ai to frp vhost ports"
echo "  2. Distribute the auth token to users"
echo "  3. Test with: frpc -c frpc.toml"
echo ""
