-- Migration: Create tunnel_access_keys table (JWT/API keys for FRP tunneled subdomains)
-- Purpose: Even if frpc authenticates to frps, requests to *.silverqueen.pro should be denied
--          until a valid access key is presented. Keys are generated by users, stored
--          in MySQL (hashed), and viewable by admins.

CREATE TABLE IF NOT EXISTS `tunnel_access_keys` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT UNSIGNED NOT NULL,
    `subdomain` VARCHAR(63) NOT NULL,
    `jti` VARCHAR(64) NOT NULL COMMENT 'JWT ID / unique key identifier',
    `token_hash` VARCHAR(64) NOT NULL COMMENT 'sha256 of the full presented token',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `expires_at` DATETIME DEFAULT NULL,
    `last_used_at` DATETIME DEFAULT NULL,
    `revoked` TINYINT(1) NOT NULL DEFAULT 0,
    `revoked_at` DATETIME DEFAULT NULL,

    UNIQUE KEY `idx_token_hash` (`token_hash`),
    UNIQUE KEY `idx_jti` (`jti`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_subdomain_active` (`subdomain`, `revoked`, `expires_at`),

    CONSTRAINT `fk_tunnel_access_keys_user`
        FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
